name: CI for Laravel with Pest

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Altere para a versão do PHP que você está usando
          extensions: dom, curl, mbstring, zip, sqlite

      - name: Install Composer dependencies
        working-directory: ./backend  # Define o diretório de trabalho para o Laravel
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare environment
        working-directory: ./backend  # Define o diretório de trabalho para o Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --env=testing  # Execute migrações se necessário

      - name: Run Pest tests
        working-directory: ./backend
        run: vendor/bin/pest